"""empty message

Revision ID: 1067ae160f07
Revises: 4a3f2aa93bd5
Create Date: 2017-12-04 17:58:28.579977

"""

# revision identifiers, used by Alembic.
revision = '1067ae160f07'
down_revision = '4a3f2aa93bd5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='email',
        column_name='body',
        type_=sa.Unicode
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name='email',
        column_name='body',
        type_=sa.JSON
    )
    # ### end Alembic commands ###
